# Generated by Django 5.1 on 2024-09-25 16:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Restourant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('adress', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('table_id', models.AutoField(primary_key=True, serialize=False)),
                ('price', models.IntegerField()),
                ('num', models.IntegerField()),
                ('status', models.CharField(choices=[('вільний', 'Вільний'), ('зайнятий', 'Зайнятий'), ('в очікуванні', 'В очікуванні')], default='вільний', max_length=20)),
                ('res_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking_app.restourant')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('status', models.CharField(choices=[('Прийшов', 'Прийшов'), ('В очікуванні', 'В очікуванні'), ('Неприйшов', 'Неприйшов')], default='В очікуванні', max_length=20)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('res_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking_app.restourant')),
                ('table_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking_app.table')),
            ],
        ),
    ]
