# Generated by Django 5.1 on 2024-10-02 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Restourant',
            new_name='Restaurant',
        ),
    ]
