# Generated by Django 5.1 on 2024-10-17 14:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_app', '0002_rename_restourant_restaurant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='res_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tables', to='booking_app.restaurant'),
        ),
    ]
