# Generated by Django 5.1 on 2024-10-17 14:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_app', '0003_alter_table_res_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='res_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking', to='booking_app.restaurant'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='table_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking', to='booking_app.table'),
        ),
    ]
