# Generated by Django 5.1 on 2024-10-17 14:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_app', '0004_alter_booking_res_name_alter_booking_table_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='res_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='booking_app.restaurant'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='table_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='booking_app.table'),
        ),
    ]
