# Generated by Django 5.1 on 2024-11-23 12:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_app', '0005_alter_booking_res_name_alter_booking_table_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='end_time',
            field=models.TimeField(default=datetime.datetime(2024, 11, 23, 12, 26, 54, 91623, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AddField(
            model_name='booking',
            name='start_time',
            field=models.TimeField(default=datetime.datetime(2024, 11, 23, 12, 26, 54, 91623, tzinfo=datetime.timezone.utc)),
        ),
    ]
